/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AffichListFilms: typeof import('./src/components/AffichListFilms.vue')['default']
    AfiichListFilms: typeof import('./src/components/AfiichListFilms.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Films: typeof import('./src/components/Films.vue')['default']
    FormText: typeof import('./src/components/FormText.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
