/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AffichListMedicaments: typeof import('./src/components/AffichListMedicaments.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    FormText: typeof import('./src/components/FormText.vue')['default']
    Medicaments: typeof import('./src/components/Medicaments.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
