/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/pageAbout': RouteRecordInfo<'/pageAbout', '/pageAbout', Record<never, never>, Record<never, never>>,
    '/pageActeurs': RouteRecordInfo<'/pageActeurs', '/pageActeurs', Record<never, never>, Record<never, never>>,
    '/pageChoix1': RouteRecordInfo<'/pageChoix1', '/pageChoix1', Record<never, never>, Record<never, never>>,
    '/pageChoix2': RouteRecordInfo<'/pageChoix2', '/pageChoix2', Record<never, never>, Record<never, never>>,
    '/pageFilms': RouteRecordInfo<'/pageFilms', '/pageFilms', Record<never, never>, Record<never, never>>,
    '/pageItem1': RouteRecordInfo<'/pageItem1', '/pageItem1', Record<never, never>, Record<never, never>>,
    '/pageItem2': RouteRecordInfo<'/pageItem2', '/pageItem2', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/pageAbout.vue': {
      routes: '/pageAbout'
      views: never
    }
    'src/pages/pageActeurs.vue': {
      routes: '/pageActeurs'
      views: never
    }
    'src/pages/pageChoix1.vue': {
      routes: '/pageChoix1'
      views: never
    }
    'src/pages/pageChoix2.vue': {
      routes: '/pageChoix2'
      views: never
    }
    'src/pages/pageFilms.vue': {
      routes: '/pageFilms'
      views: never
    }
    'src/pages/pageItem1.vue': {
      routes: '/pageItem1'
      views: never
    }
    'src/pages/pageItem2.vue': {
      routes: '/pageItem2'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
